<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Widgets
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Include widget class files
require_once( get_stylesheet_directory() . '/widgets/custom-featured-post-widget.php' );

add_action( 'widgets_init', 'load_widgets' );
/**
 * Register widgets for use in the Genesis theme.
 *
 * @since 1.7.0
 */
function load_widgets() {

	register_widget( 'Custom_Featured_Post' );

}