<?php
#
# Email Sender
# 
# Sends emails to both the client and staff, 'client' and 'internal'.
# Reads from templates in ./emails/inlined, which can be generated by ./readEmail.php
# Can also read non-inlined, but those emails will not be be 'optimized' with inlined styling
# thus may not be totally consistant. 
# 
# ~April 05 2014
# 

error_reporting(E_ALL);

require_once "../../../../wp-load.php"; # Adds wordpress functionality
require_once 'helpers.php'; # helper functions

# Serves content to the client and also ends the script
function endRequest($json, $redirect = '') {
	if ( $redirect ) {
		header("location: $redirect"); # Apparently php sends a 302 with this automatically
	} else {
		header("content-type: application/json");
		echo json_encode($json);
	}
}

$json = array( 'success' => false, 'error' => null );

$readEmail	= isset($readEmail)		? $readEmail	: false;
$doEmail	= isset($doEmail)		? $doEmail		: true;
$useInlined	= isset($useInlined)	? $useInlined	: true;
$apiCall	= isset($apiCall)		? $apiCall		: null;

# If redirect is set, redirect instead of serving json (ie. no javascript is needed)
# This should really be a valid redirect path or nothing
$redirect		= !empty($_GET['redirect']) ? $_GET['redirect'] : '';

$nowDate		= new DateTime( "now", new DateTimeZone("Australia/Queensland") );
$sentDateTime	= $nowDate->format("m-d-y H:i:s A");

$ltscRoot = get_bloginfo('wpurl');
$pagePath = $_GET['page'];

$ltscPdf = "http://ltsc.wpengine.com/wp-content/uploads/2014/04/LTSC-OVERVIEW-VII.pdf";

$client_name		= $_GET['name'];
$client_email		= $_GET['email'];
$client_phone		= $_GET['phone'];
$client_postCode	= $_GET['postCode'];
$client_country		= $_GET['country'];

# Optionals
$client_text			= $_GET['text'];
$client_birthDate		= $_GET['birthDate'];
$client_ownsProperty	= $_GET['ownsProperty'];
$client_income			= $_GET['income'];

$client_isMotorsport	= !! $_GET['motorsport'];

if ( $apiCall !== false ) { $apiCall = $client_isMotorsport; }

$client_extraFields = !! ( $client_text || $client_birthDate || $client_ownsProperty || $client_income );

$client_countryCode =
$client_countryName = '';

include '../data.php';

foreach($data['countries'] as $code => $name) {
	if ( $client_country == $code ) {
		$client_countryCode = $code;
		$client_countryName = $name;
		break;
	}
}

if ( $client_isMotorsport ) {
	$client_subject = 'Motorsport Competition Entry - LTSC';
	$emailTemplate = 'motorsport';
} else {
	$client_subject = 'LTSC Contracts - Tomorrows Property Today';
	$emailTemplate = isset($emailTemplate) ? $emailTemplate : 'generic';
}

$templatePath = 'emails/';

if ( $useInlined ) {
	$templatePath = 'emails/inlined/';
}

# hold the buffer, include whatever, then releaseBuffer() to grab any content that would normally be echoed.
holdBuffer();

include $templatePath . $emailTemplate . '.php';

$client_body = releaseBuffer();

# Internal email

if ( ! isset($internal_email) ) $internal_email = "info@cottonparkestate.com";

$internal_subject = 'LTSC Enquiry: ' . strtoupper($emailTemplate) . ' - ' . $pagePath;

# Do the same as we did for $client_body
holdBuffer();

include 'emails/internal.php';

$internal_body = releaseBuffer();

if ( ! $readEmail ) {
	/*# TEST

	$internal_email		=
	$client_email		= 'sam.johnson@ariongroup.com.au';
	$doEmail = true;

	# TEST*/
}

#$doEmail = false; # test
#$redirect = '';

$client_headers		= "mime-version: 1.0\r\n";
$client_headers		.= "content-type: text/html; charset=utf-8\r\n";

$internal_headers	= $client_headers;

$client_headers		.= "To:$client_email\r\n";
$client_headers		.= "From:$internal_email\r\n";

$internal_headers	.= "To:$internal_email\r\n";
$internal_headers	.= "From:$internal_email\r\n";


if ( $doEmail ) {
	# internal email
	$test_email		= 'sam.johnson@ariongroup.com.au';
	$test_headers	= "mime-version: 1.0\r\n";
	$test_headers	.= "content-type: text/html; charset=utf-8\r\n";
	$test_headers	.= "To:$test_email\r\n";
	$test_headers	.= "From:$test_email\r\n";

	$json['internalSuccess']	= mail($internal_email, $internal_subject, $internal_body, $internal_headers);
	$json['success']			= mail($client_email, $client_subject, $client_body, $client_headers);

	sleep(1); # I guess wait a bit so that the email is known to be sent? consider removing this.

	$json['testInternalSuccess']	= mail($test_email, $internal_subject, $internal_body, $test_headers);
	$json['testSuccess']			= mail($test_email, $client_subject, $client_body, $test_headers);

}



if ( ! $readEmail ) {
	endRequest($json, $redirect);
}

if ( $apiCall ) {
	include 'apiCall.php';

	#$json['apiCall'] = $apiCallResult;
	#$json['apiError'] = $apiError;
}
?>