<?php
/*
Template Name: Privacy Policy
 */
?>
<!DOCTYPE html>
<html>
	<head>
		<title><?php bloginfo( 'name' ); ?></title>
		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link href='//fonts.googleapis.com/css?family=Open+Sans:600,400,300' rel='stylesheet' type='text/css'>
		<link media="screen" type="text/css" href="<?php echo get_stylesheet_directory_uri() ?>/terms.css?version=24" rel="stylesheet" />
	</head>
	<body>
		<div class="container">
			<h1 class="title">
				Privacy Policy
			</h1>

			<h3>1. INTRODUCTION</h3>

			<p>This Privacy Policy describes our practices in connection with information collected through all our services including advertising services, websites, mobile sites, applications (“apps”), and widgets, competitions and customer surveys (collectively, the “ArionGroup Services”). By using ArionGroup Services, you agree to the terms and conditions of this Privacy Policy.</p>

			<p>This Privacy Policy applies to all persons who interact with us, including those who are advertisers, subscribers to our goods or services and registered and unregistered users of ArionGroup Services. This Privacy Policy applies to ArionGroup’s collection and use of your personal information (i.e. information about an identified or reasonably identifiable individual, such as full name or name and postal address).</p>

			<p>ArionGroup is bound by the Privacy Act 1988 (Cth) in relation to the handling of personal information. Where appropriate we will handle personal information relying on the media exemption (and complying with the Australian Press Council Privacy Standards), related bodies corporate exemption and the employee records exemption in the Act. This Privacy Policy will not address issues around personal information and its collection and use in the course of journalism and for details on this, you should refer to the Australian Press Council Privacy Standards at http://www.presscouncil.org.au/privacy-principles.</p>

			<h3>2. WHAT INFORMATION DO WE COLLECT?</h3>

			<p>ArionGroup collects the personal information needed to provide ArionGroup Services and for our business operations. If you choose not to provide certain personal information to us, we may not be able to provide you with the services you require. The following are the main types of personal information collected by ArionGroup and the main purposes for which they are collected.</p>
			<p>Registration Information is the information you provide to ArionGroup in the course of registering for or acquiring a ArionGroup Service, for example, to create an account, become a subscriber, become an advertiser, post comments, receive a newsletter, or enter a competition. Registration Information may include, for example, name, delivery or postal address, email address, gender and birthday. It includes additional information which you provide to ArionGroup in the course of that relationship. Where possible you may have the option of interacting with us anonymously (for example when browsing our digital products as a casual user) or using a pseudonym. We will usually make it clear whenever this is an option.</p>
			<p>Public Information and Posts consist of comments or content that you post to the ArionGroup Services and the information about you that accompanies those posts or content, which may include a name, user name, comments, likes, tweets, status, profile information and picture(s). Public Information and Posts are always public, which means they are available to everyone and may be displayed in search results on external search engines.</p>
			<p>Information from third party Social Media. If you access or log-in to a ArionGroup Service through a third party social media service or connect a ArionGroup Service to a third party social media service, the information we collect may also include your user ID and/or user name associated with that social media service, any information or content you have permitted the third party social media service to share with us, such as your profile picture, email address, followers or friends lists, and any information you have disclosed in connection with that social media service. We do not collect your passwords other than in relation to our own services. When you access the ArionGroup Services through third party social media services or when you connect a ArionGroup Service to third party social media services, you are authorizing ArionGroup to collect, store use and disclose such information and content in accordance with this Privacy Policy.</p>
			<p>Activity Information – cookies and other technologies.</p>

			<p>When you access and interact with the ArionGroup Services, we may collect certain information about those visits. For example, in order to permit your connection to the ArionGroup Services, our servers receive and record information about your computer, device, and browser, including potentially your IP address, browser type, and other software or hardware information. If you access the ArionGroup Services from a mobile or other device, we may collect a unique device identifier assigned to that device, geolocation data, or other transactional information from that device.</p>
			<p>Cookies and other tracking technologies (such as browser cookies and local storage, pixel beacons, and Adobe Flash technology including cookies) are comprised of small bits of data or code that often include a de-identified or anonymous unique identifier. Websites, apps and other services send this data to your browser when you first request a web page and then store the data on your computer so that such websites, apps and other services can access information when you make subsequent requests for pages from that service. These technologies may also be used to collect and store information such as pages you have visited, content you have viewed, search queries you have run and advertisements you have viewed in relation to your usage of the ArionGroup Services and other websites you have visited.</p>
			<p>Third parties that support the ArionGroup Services by serving advertisements or providing services, such as allowing you to share content or tracking aggregate ArionGroup Services usage statistics, may also use these technologies to collect similar information. ArionGroup does not control these third-party technologies and their use is governed by the privacy policies of those third parties using such technologies.</p>
			<p>Most browsers are initially set to accept cookies, but you can change your settings to notify you when a cookie is being set or updated, or to block cookies altogether. Please consult the "Help" section of your browser for more information. Users can manage the use of Flash technologies, with the Flash management tools available at Adobe’s website. Please note that by blocking any or all cookies you may not have access to certain features, content or personalization available through the ArionGroup Services.</p>

			<p><b>Information from Other Sources.</b> We may supplement the information we collect with information from other sources, such as commercially available sources and data providers, as well as information from our business partners or related and affiliated companies in Australia or internationally.</p>

			<p><b>Information in relation to other persons who deal with us.</b> When you apply for a job or contract with us we may collect certain information from you or from any recruitment consultant, your previous employers and others who may be able to provide information to assist us in deciding whether or not to make you an offer of employment or engage you under a contract. This Privacy Policy does not apply to acts and practices in relation to employee records of our current and former employees which are exempt from the Privacy Act.</p>
			<p>ArionGroup also collects personal information about individuals who are, or are employed by, our suppliers (including service and content providers), contractors, dealers, related companies, agents and corporate customers. Generally, if appropriate, we will state why we are collecting personal information when we collect it and how we plan to use it, or these things will be obvious when we collect the information.</p>


			<h3>3. HOW DO WE USE YOUR INFORMATION?</h3>

			<p>We use the information we collect from and about you to provide the ArionGroup Services and features to you, including: to measure and improve those ArionGroup Services and features; to improve your experience with both online and off-line ArionGroup Services by delivering content ArionGroup believes you are likely to find relevant and interesting, including advertising and marketing messages; to allow you to comment on content, and participate in games, competitions, or rewards programs; to provide you with customer support and to respond to inquiries. When you are not reasonably identifiable in relation to the information collected from or about you, we may use that information for any purpose or share it with third parties. We may also de-identify the information we collect about you so that we can use and disclose it without using or revealing any personal information about you.</p>
			<p>We use the information we collect from and about you for these additional purposes:</p>
			<p>To provide ArionGroup Services to you. ArionGroup will use your information to provide ArionGroup Services to you, to fulfill administrative functions associated with these services (for example billing, credit and account management), to enter into contracts with you or third parties and for marketing and client relationship purposes. Where your information is contained within an advertisement which ArionGroup publishes for you, ArionGroup may also use your information for publication of that same advertisement in other media, in accordance with the terms and conditions applicable to the initial publication of the advertisement. We may also use your information to improve ArionGroup Services including through research and data analysis by us and our service providers. Where your personal information is contained in a user generated post or in a communication to an editor or journalist, we may publish your name and suburb to identify you as the author of the comment/correspondence if we choose to publish comment/correspondence in any media. We may use and disclose your personal information in other ways expressly disclosed at the point of collection. If you are a competition winner we may disclose your information to relevant regulatory authorities and publish your details in accordance with the competition terms.</p>
			<p>To allow service and content providers to assist us in providing and managing the ArionGroup Services. ArionGroup may make your information available to certain third party service and content providers, such as providers of data cloud services, website hosting service providers, debt collection services and direct marketing services, who help us manage or provide the ArionGroup Services or provide ArionGroup with related services. These third parties may be located in a range of different countries including the United Kingdom, United States of America and Singapore. ArionGroup generally requires these service and content providers to comply with relevant privacy laws and not to use personal information which ArionGroup provides for any purpose other than the specific service they are providing to you and/or ArionGroup.</p>
			<p>To allow social sharing functionality. If you log in with or connect a social media service account with ArionGroup Services, we may share your user name, picture, tweets and likes, as well as your activities and comments with other ArionGroup Services users and with your friends associated with your social media service. We may also share the same information with the social media service provider. By logging in with or connecting your ArionGroup Services account with a social media service, you are authorizing us to share information we collect from and about you with the social media service provider, other users and your friends and you understand that the social media service’s use of the shared information will be governed by the social media service’s privacy policy. If you do not want your personal information shared in this way, please do not connect your social media service account with your ArionGroup Services account and do not participate in social sharing on ArionGroup Services.</p>
			<p>To provide co-branded services and features. We may offer co-branded services or features, such as competitions or other promotions together with a third party (“Co-Branded Services”). These Co-Branded Services may be hosted on ArionGroup Services or on the third party’s service. By virtue of these relationships, we may share the information you submit in connection with the Co-Branded Service with the third party. The third party’s use of your information will be governed by the third party’s privacy policy. We will advise you when this is occurring or obtain your express consent to share your personal information in these circumstances.</p>
			<p>To deliver relevant advertisements. ArionGroup and our advertisers may use the information we collect from and about you to deliver relevant ads to you when you use the ArionGroup Services or another service. Please refer to Section 6 below for information about your choices in connection with the advertisements you see when using the ArionGroup Services.</p>
			<p>To contact you. ArionGroup may periodically send promotional materials or notifications which it believes might be of interest to you. Promotional materials may include invitations to participate in various activities (such as customer surveys) or special offers.</p>
			<p>To share with our ArionGroup Affiliates. ArionGroup may share your information with ArionGroup’s related companies both in and outside of Australia including in United Kingdom and United States of America. Users who visit our related companies’ services should still refer to their separate privacy policies, which may differ in some respects from this Privacy Policy. Where we share your information with our related companies, they may use your information in the same way as we can under this Privacy Policy.</p>
			<p>To share with business partners. Where you have expressly consented to this, ArionGroup may share your information with business partners to permit them to send you marketing communications consistent with your choices.</p>
			<p>To protect the rights of ArionGroup and others. There may be instances when ArionGroup may disclose your information, including situations where ArionGroup has a good faith belief that such disclosure is necessary in order to: (i) protect, enforce, or defend the legal rights, privacy, safety, or property of ArionGroup, our related companies or their employees, agents and contractors (including enforcement of our agreements and our terms of use); (ii) protect the safety, privacy, and security of users of the ArionGroup Services or members of the public; (iii) protect against fraud or for risk management purposes; (iv) comply with the law or legal process in any country; or (v) respond to requests from public and government authorities.</p>
			<p>To complete a merger or sale of assets. If ArionGroup sells all or part of its business or makes a sale or transfer of its assets or is otherwise involved in a merger or transfer of all or a material part of its business, ArionGroup may transfer or disclose your information to the party or parties involved in the transaction as part of that transaction and as part of any due diligence processes which take place in contemplation of a potential transaction.</p>

			<h3>4. HOW DO WE PROTECT YOUR INFORMATION?</h3>

			<p>ArionGroup uses commercially reasonable administrative, technical, personnel and physical measures to safeguard information in its possession against loss, theft and unauthorized use, disclosure or modification. However, no one can guarantee the complete safety of your information.</p>

			<h3>5. HOW CAN YOU ACCESS YOUR INFORMATION?</h3>

			<p>If you would like to access, review, correct or update your personal information, you may contact us as outlined in section 7 of this policy. In your request, please include your email address, name, address, and telephone number and specify clearly what information you would like to access, review, correct or update. We will need to share your information with others who can assist in responding to your request. We will try to respond to your request as soon as reasonably practicable. If we deny access in any circumstances we will generally tell you why.</p>

			<h3>6. HOW CAN YOU OPT OUT?</h3>

			<p>You can block or delete cookies through your browser settings but be aware that if you do this you may not be able to continue to receive some ArionGroup Services. In addition, this may not be sufficient to block or opt-out of all activities which track the usage of a device or which deliver targeted content. If you wish to obtain more information about how your previous usage of the Internet may be used to determine the ads that you see when you use the ArionGroup Services, go to http://youronlinechoices.com.au and to opt out of receiving this type of advertising go to http://www.youronlinechoices.com.au/opt-out.</p>
			<p>If you want to stop receiving promotional materials, you can change your account settings or follow the unsubscribe instructions at the bottom of each email or text message. If you have installed a mobile app and you wish to stop receiving push notifications, you can change the settings either on your mobile device or through the app.</p>
			<p>If you have linked any of your social media accounts to your account for any ArionGroup Services, you can cancel that link by changing your account settings.</p>
			<p>If you need any assistance with changing your account settings, please call ArionGroup.</p>

			<h3>7. OTHER IMPORTANT INFORMATION FOR YOU</h3>

			<p><b>Updates to Privacy Policy.</b> ArionGroup may modify this Privacy Policy at any time. Please look at the Last Updated date at the top of this Privacy Policy to see when this Privacy Policy was last revised. Any changes to this Privacy Policy will become effective when we post the revised Privacy Policy on the ArionGroup Services. If the changes affect any agreement between us, you will be entitled to terminate our agreement if those changes are not acceptable to you, on reasonable grounds.</p>

			<p><b>Location of Data.</b> Some of the ArionGroup Services are hosted in and managed outside of Australia and in dealing with ArionGroup, you consent to having any personal information accessible from or transmitted outside of Australia.</p>

			<p><b>Linked Services.</b> The ArionGroup Services may also be linked to sites operated by unaffiliated companies, and may carry advertisements or offer content, functionality, games, newsletters, competitions or applications developed and maintained by unaffiliated companies. ArionGroup is not responsible for the privacy practices of unaffiliated companies, and once you leave the ArionGroup Services or click an advertisement you should check the applicable privacy policy of the other service.</p>

			<p><b>Collection of Personal Financial Information by a Payment Service.</b> In some cases, we may use an unaffiliated payment service to allow you to purchase a product or make payments (“Payment Service”). If you wish to purchase a product or make a payment using a Payment Service, you will be directed to a Payment Service webpage. Any information that you provide to a Payment Service will be subject to the applicable Payment Service's privacy policy, rather than this Privacy Policy. We have no control over, and are not responsible for, any Payment Service's use of information collected through any Payment Service.</p>

			<p><b>Data Retention.</b> We will retain your information for the period necessary to fulfill the purposes outlined in this Privacy Policy unless a longer retention period is required or allowed by law.</p>
			<p>Remember that even after you cancel your account, copies of some information from your account may remain viewable in some circumstances where, for example, you have shared information with social media or other services. Because of the nature of caching technology, your account may not be instantly inaccessible to others. We may also retain backup information related to your account on our servers for some time after cancelation for fraud detection or to comply with applicable law or our internal security or other policies. We do not always completely remove or delete all of your information for a number of reasons including due to technical and systems constraints, contractual, financial or legal requirements.</p>

			<p><b>Sensitive Information.</b> We ask that you not send us, and you not disclose, any sensitive personal information (such as information related to racial or ethnic origin, religion or other beliefs, health, criminal background or trade union membership) on or through the ArionGroup Services or otherwise. If, contrary to this request, you do provide any sensitive information, in doing so you consent to us collecting and handling that information in accordance with this Privacy Policy.</p>

			<p><b>Complaint.</b> If you think we have breached the Privacy Act or other applicable privacy laws, you may complain to us by contacting us as outlined in section 8 below. When you contact us, please include your email address, name, address, and telephone number and clearly describe your complaint. We will need to share your information with others who can assist in responding to your complaint. We will respond to your complaint as soon as reasonably practicable and in any event within 5 business days, by making contact with you to inform you whether we have accepted your complaint, need further information or do not think we are in breach. We will also let you know the next steps in resolving your complaint. If you are not satisfied with our response to your complaint, or at any time, you may refer your complaint to the Office of the Australian Information Commissioner (www.oaic.gov.au).</p>

			<h3>8. HOW YOU CAN CONTACT US</h3>

			<p>If you have questions about this Privacy Policy, please contact us:</p>

			<p><b>Phone:</b> 1800 177 199
			<br/>
			<b>Email:</b> info@ariongroup.com.au</p>
			
			<br/>
		</div>
	</body>
</html>